name: Build for all platforms

on:
  pull_request: {}
  push: { branches: [develop] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  PROJECT_PATH: UnityProject
  BUILD_NAME: Unitystation

jobs:
  buildForLinux:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: webbertakken/unity-activate@v1
      - uses: reavershark/unity-build@v0.2
        id: buildStep
        env:
          BUILD_TARGET: StandaloneLinux64
      - uses: actions/upload-artifact@v1
        with:
          name: LinuxBuild
          path: ${{ steps.buildStep.outputs.buildPath }}
